apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
  namespace: laravel
type: Opaque
# ATENÇÃO: Substitua os valores abaixo por base64 real antes de aplicar
# Para codificar: echo -n "valor" | base64
stringData:
  APP_KEY: "base64:OpybUfM+KJ3OnpeGdb/kmOsT76UZ2DaorviSkkRDl78="
  DB_PASSWORD: "secret"
  REDIS_PASSWORD: ""
  AWS_ACCESS_KEY_ID: "sail"
  AWS_SECRET_ACCESS_KEY: "password"
  MINIO_ROOT_USER: "sail"
  MINIO_ROOT_PASSWORD: "password"
